name: geo-ds-lab-cholera
dependencies:
- cartopy=0.21.1
- folium=0.14.0
- geopandas=0.12.2
- geoviews=1.9.6
- hvplot=0.8.3
- ipykernel=6.21.2
- jupyter=1.0.0
- matplotlib=3.6.3
- pandas=1.5.3
- pyproj=3.5.0
- python=3.9