name: geo-ds-cholera
channels:
- conda-forge
dependencies:
- black[jupyter]=23.3.0
- folium=0.14.0
- geopandas=0.12.2
- ipykernel=6.21.2
- matplotlib=3.6.3
- nbdev=2.2.10
- pandas=1.5.3
- pre-commit=3.2.2
- python=3.11.3
