name: geo-ds-cholera
channels:
- conda-forge
- fastai
dependencies:

- black[jupyter]~=23.3
- bottleneck
# - cartopy
- dask
# - folium
# - geojson-pydantic
- geopandas
# - geopy
# - geoviews
# - holoviews
# - hvplot
- ipykernel
- matplotlib
- nbdev
- nbformat
- netCDF4
- numexpr
- pandas
# - plotly
- pooch
- pre-commit~=3.3
# - pyproj
- python~=3.10.0
- rasterio~=1.3.8
- regionmask
- requests
- rioxarray
- xarray
- xarray-spatial
