name: geo-ds-cholera
channels:
- conda-forge
- fastai
dependencies:
- aiohttp=3.8.4
- black[jupyter]=23.3.0
- cartopy=0.21.1
- folium=0.14.0
- geojson-pydantic=0.6
- geopandas=0.12.2
- geoviews=1.5.0
- holoviews=1.15.4
- hvplot=0.8.3
- ipykernel=6.21.2
- matplotlib=3.6.3
- nbdev=2.2.10
- nbformat=5.8.0
- pandas=1.5.3
- pre-commit=3.2.2
- plotly=5.14.1
- pyproj=3.5.0
- python=3.11.3
- requests=2.28.2
- thefuzz[speedup]=0.19.0
