name: geo-ds-cholera
channels:
- conda-forge
- fastai
dependencies:
- aiohttp~=3.8
- black[jupyter]~=23.3
- cartopy~=0.21
- folium~=0.14
- geojson-pydantic~=0.6
- geopandas~=0.12
- geopy~=2.3
- geoviews~=1.9
- holoviews~=1.16
- hvplot~=0.8
- ipykernel~=6.23
- matplotlib~=3.6
- nbdev~=2.2
- nbformat~=5.8
- pandas~=2
- plotly~=5.14
- pre-commit~=3.3
- pycountry~=22.3
- pyproj~=3.5.0
- python>=3.11
- requests~=2.31
- thefuzz[speedup]~=0.19.0
