name: geo-ds-cholera
channels:
- conda-forge
dependencies:
- black-jupyter~=23.3
- bottleneck
- folium
- geopandas
- ipykernel
- matplotlib
- nbdev
- nbformat
- netCDF4
- numexpr
- pandas~=2.0
- plotly
- pre-commit
- python~=3.11.0
- rasterio
- regionmask
- requests
- rioxarray
- xarray
- xarray-spatial
