name: geo-ds-cholera
channels:
- conda-forge
- fastai
dependencies:
- folium=0.14.0
- geopandas=0.12.2
- ipykernel=6.21.2
- matplotlib=3.6.3
- pandas=1.5.3
- python=3.11.3
- requests=2.28.2
- thefuzz[speedup]=0.19.0
