name: geo-ds-cholera
channels:
- conda-forge
- fastai
dependencies:
- black-jupyter~=23.3
- bottleneck
- dask
- dask-labextension
# xarray uses flox for better `groupby` performance
- flox
- folium
- geopandas
- imbalanced-learn
- ipykernel
- jupyterlab
- matplotlib
- nbdev~=2.3
- nbformat
- netCDF4
- numexpr
- pandas~=2.0
- pip
- plotly
- pre-commit
- python~=3.11.0
- python-dotenv
- rasterio
- regionmask
- rioxarray
# stamina retries failed operations
- stamina
# stamina automatically writes log entries via structlog, when installed
- structlog
- xarray
- pip:
  # CEDA OPeNDAP access requires a certificate
  - ContrailOnlineCAClient
  - missingno
