name: geo-ds-cholera
channels:
- conda-forge
- fastai
dependencies:

# - aiohttp
- black[jupyter]>=23.3
# - cartopy
# - folium
# - geojson-pydantic
- geopandas
# - geopy
# - geoviews
# - holoviews
# - hvplot
- ipykernel
- matplotlib
- nbdev
- nbformat
- netCDF4
- pandas
# - plotly
- pooch
- pre-commit>=3.3
# - pycountry
# - pyproj
- python>=3.10
- rasterio>=1.3.8
- regionmask
- requests
- rioxarray
# - thefuzz[speedup]
- xarray[accel,parallel]
- xarray-spatial
